# Custom Language File for the Cryptalis Launcher

[ejs.app]
title = "Cryptalis Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/CryptalisOfficial/CryptalisLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/vj5fSjeCfx"

[ejs.settings]
sourceGithubLink = "https://github.com/CryptalisOfficial/CryptalisLauncher"
supportLink = "https://github.com/CryptalisOfficial/CryptalisLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Cryptalis"
welcomeDescription = "Enter the world of **Cryptalis**, a universe where technology and magic clash for control of reality itself. Join powerful factions, explore cursed realms, and uncover the buried secrets of a world torn between shadow and light. Every choice, every battle, and every alliance will shape your destiny in this ever-changing realm."
welcomeDescCTA = "Your adventure begins now. Prepare to dive into the world of Cryptalis."
