# Fichier de langue FR pour Cryptalis Launcher

[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D’UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d’un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n’est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n’est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"

tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez ou gérez vos comptes existants."
microsoftAccount = "Compte Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Compte Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"

minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique au serveur au lancement."
launchDetachedTitle = "Lancer le jeu séparément du launcher."
launchDetachedDesc = "Si le jeu n’est pas détaché, fermer le launcher fermera également le jeu."

tabModsHeaderText = "Paramètres des Mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods obligatoires"
optionalMods = "Mods optionnels"
dropinMods = "Mods personnalisés"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activez ou désactivez les shaders. Les shaders nécessitent une configuration puissante. Vous pouvez ajouter vos packs personnalisés ici."
selectShaderpack = "Sélectionner un shaderpack"

tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "Le minimum recommandé est de 3 Go. Mettre les mêmes valeurs min et max peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner un exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L’exécutable Java est vérifié avant le lancement."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options passées à la JVM. Ne pas inclure <em>-Xms</em> ou <em>-Xmx</em>."

launcherTabHeaderText = "Paramètres du Launcher"
launcherTabHeaderDesc = "Options liées au launcher Cryptalis."
allowPrereleaseTitle = "Autoriser les préversions."
allowPrereleaseDesc = "Les préversions peuvent contenir des fonctionnalités en test.<br>Ce paramètre est toujours actif si vous utilisez une version bêta."
dataDirectoryTitle = "Dossier de données"
selectDataDirectory = "Choisir le dossier de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations locales de Java seront stockés ici.<br>Les captures d’écran et mondes sont enregistrés dans le dossier de l’instance correspondante."

aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Informations et notes de version du launcher."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Code source (GitHub)"
support = "Assistance"
devToolsConsole = "Console développeur"
releaseNotes = "Notes de version"
changelog = "Journal des changements"
noReleaseNotes = "Aucune note disponible"
viewReleaseNotes = "Voir sur GitHub"

launcherUpdatesHeaderText = "Mises à jour du Launcher"
launcherUpdatesHeaderDesc = "Téléchargez et installez les mises à jour disponibles."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client.."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s’est produite. Consultez la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse du système.."
noCompatibleJava = "Aucune installation Java<br>compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous devez avoir Java {major} 64 bits. Voulez-vous que nous l’installions ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java.."
javaDownloadFailureTitle = "Erreur lors du téléchargement"
javaDownloadFailureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
javaRequired = "Java requis<br>pour le lancement"
javaRequiredMessage = 'Une installation valide de Java {major} x64 est requise.<br><br>Voir le <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide d’installation manuelle</a>.'
javaRequiredDismiss = "J’ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une distribution OpenJDK."
javaDownloadCorruptedError = "Le fichier téléchargé est corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur.."
fatalError = "Erreur critique"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console (CTRL + Maj + i)."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir la console (CTRL + Maj + i) pour plus d’informations."
validatingFileIntegrity = "Vérification de l’intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur pendant la vérification"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur pendant le téléchargement"
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n’a pas été téléchargé correctement. Le jeu ne peut pas démarrer.<br><br>Désactivez temporairement votre antivirus et relancez le jeu.<br><br>Merci de <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signaler le problème</a>."
doneEnjoyServer = "Terminé. Profitez du serveur Cryptalis !"
checkConsoleForDetails = "Consultez la console pour plus d’informations."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Connexion à Cryptalis.."
joined = "Exploration du royaume !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur est survenue"
errorMessage = "Échec de l’authentification Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur est survenue"
errorMessage = "Échec de la déconnexion Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Vous devez être connecté à au moins un compte pour utiliser le launcher.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Confirmer"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d’utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n’est pas utilisé, puis réessayez."
failedToggleTitle = "Échec de l’activation<br>d’un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Préversion"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle préversion disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et exécutez le fichier pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification en cours.."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Impossible d’authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur critique : impossible de charger l’index"
fatalErrorMessage = "Connexion impossible aux serveurs Cryptalis pour récupérer l’index de distribution.<br><br>Assurez-vous d’être connecté à Internet, puis relancez l’application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec du rafraîchissement du compte"
failedMessage = "Impossible de rafraîchir la connexion pour <strong>{account}</strong>. Sélectionnez un autre compte ou reconnectez-vous."
failedMessageSelectAnotherAccount = "Connexion expirée pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil Minecraft manquant"
noProfileDesc = "Votre compte Microsoft n’a pas encore de profil Minecraft. Configurez-le sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur :<br>Compte Xbox manquant"
noXboxAccountDesc = "Votre compte Microsoft n’a pas de compte Xbox associé."
xblBannedTitle = "Erreur :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte est dans une région où Xbox Live est indisponible."
under18Title = "Erreur :<br>Autorisation parentale requise"
under18Desc = "Les comptes de moins de 18 ans doivent être ajoutés à une famille."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s’est produite. Consultez la console pour plus d’informations."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Merci de signaler ce problème."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Point d’accès introuvable. Merci de signaler ce problème."
accountMigratedTitle = "Erreur :<br>Compte migré"
accountMigratedDesc = "Connectez-vous avec votre adresse e-mail."
invalidCredentialsTitle = "Erreur :<br>Identifiants invalides"
invalidCredentialsDesc = "Email ou mot de passe incorrect. Réessayez."
tooManyAttemptsTitle = "Erreur :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives récentes. Réessayez plus tard."
invalidTokenTitle = "Erreur :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d’accès est invalide."
tokenHasProfileTitle = "Erreur :<br>Profil déjà associé"
tokenHasProfileDesc = "Le jeton possède déjà un profil. Non encore pris en charge."
credentialsMissingTitle = "Erreur :<br>Informations manquantes"
credentialsMissingDesc = "Nom d’utilisateur ou mot de passe manquant."
invalidSaltVersionTitle = "Erreur :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type non pris en charge"
unsupportedMediaTypeDesc = "Type de média non supporté."
accountGoneTitle = "Erreur :<br>Compte migré"
accountGoneDesc = "Compte migré vers Microsoft. Connectez-vous avec Microsoft."
unreachableTitle = "Erreur :<br>Serveur injoignable"
unreachableDesc = "Impossible d’atteindre les serveurs d’authentification."
gameNotPurchasedTitle = "Erreur :<br>Jeu non acheté"
gameNotPurchasedDesc = "Ce compte n’a pas acheté Minecraft. Achetez-le sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s’est produite. Consultez la console pour plus de détails."
