name: Build

on:
  push:
    branches: [ master, main ]
    tags:
       - 'v*.*.*'

permissions:
  contents: write

concurrency:
  group: build-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      # Token auto des Actions, mappé vers ce qu'attend electron-builder
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_args: "--win nsis"
            artifact_name: windows-dist
          - os: ubuntu-latest
            build_args: "--linux AppImage"
            artifact_name: linux-dist
          - os: macos-latest
            build_args: "--mac dmg"
            artifact_name: macos-dist

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (ci or i)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      # Build sur branche (artefacts uniquement)
      - name: Build (no publish on branch)
        if: startsWith(github.ref, 'refs/heads/')
        run: npx electron-builder ${{ matrix.build_args }} -p never

      # Build + publication sur tag vX.Y.Z
      - name: Build & Publish (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: npx electron-builder ${{ matrix.build_args }} -p always

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/**
